# Generated by Django 4.2.25 on 2025-10-28 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bbnb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('sharePrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StocksAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.IntegerField()),
                ('connectedBankingAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_account', to='bbnb.account')),
            ],
        ),
    ]
