# Generated by Django 4.2.25 on 2025-10-28 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=39)),
                ('savingsAccountNumber', models.CharField(max_length=39)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('userId', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
                ('loggedIn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('deposit', models.IntegerField(default=0)),
                ('fromAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='bbnb.account')),
                ('toAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='bbnb.account')),
            ],
        ),
        migrations.CreateModel(
            name='SavedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savedAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_account', to='bbnb.account')),
                ('yourAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_account', to='bbnb.account')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('percent', models.FloatField()),
                ('duration', models.IntegerField()),
                ('installment', models.FloatField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='bbnb.account')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('percent', models.FloatField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('duration', models.IntegerField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbnb.account')),
            ],
        ),
    ]
